on:  [push, pull_request]
name: ci
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pingfederate-version: [ 10.2.7, 10.3.7, 11.0.3, 11.1.1 ]
    services:
      pingfederate:
        image: ghcr.io/iwarapter/pingfederate:${{ matrix.pingfederate-version }}-edge
        env:
          PING_IDENTITY_ACCEPT_EULA: YES
          PING_IDENTITY_DEVOPS_USER: ${{ secrets.PING_IDENTITY_DEVOPS_USER }}
          PING_IDENTITY_DEVOPS_KEY: ${{ secrets.PING_IDENTITY_DEVOPS_KEY }}
          SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
          SERVER_PROFILE_PATH: getting-started/pingfederate
          IMAGE_VERSION: pingfederate-alpine-az11-${{ matrix.pingfederate-version }}-${{ needs.getdate.outputs.date }}-d9b5
        ports:
          - 9999:9999
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Install tools
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Staticcheck
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        staticcheck ./...

    - name: Check dependencies
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum || \
        	(echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
        echo "==> Checking source code with go mod vendor..."
        go mod vendor
        git diff --compact-summary --exit-code -- vendor || \
        	(echo; echo "Unexpected difference in vendor/ directory. Run 'go mod vendor' command or revert any go.mod/go.sum/vendor changes and commit."; exit 1)

    - name: Test
      run: |
        go test -mod=vendor ./... -v -trimpath -coverprofile=coverage.out
        go tool cover -func=coverage.out

